version: '3.4'

services:
  emailservice:
    image: ${DOCKER_REGISTRY-}emailservice
    ports:
      - 80
      - 443
    environment: 
      - ASPNETCORE_URLS=https://+:443;http://+:80
    build:
      context: .
      dockerfile: Dockerfile


